server:
  port: 9010

spring:
  profiles:
    active: dev
  application:
    name: s-system
  cloud:
    nacos:
      discovery:
        server-addr: node2:8088
        namespace: ${spring.profiles.active}
        group: LGD_GROUP
      config:
        server-addr: node2:8088
        namespace: ${spring.profiles.active}
        file-extension: yaml
        group: LGD_GROUP
  redis:
    lettuce:
      pool:
        maxIdle: 8
        minIdle: 2
        maxActive: 4
        maxWait: 6000
  datasource:
    initial-size: 4
    max-active: 8
    min-idle: 2
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 16
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    filters: stat,wall