server:
  port: 9010

spring:
  profiles:
    active: dev
  application:
    name: s-system
  cloud:
    nacos:
      discovery:
        server-addr: node2:8088
        namespace: ${spring.profiles.active}
        group: LGD_GROUP

  redis:
    host: node2
    port: 6378
    password: lEguanDiAn898
    timeout: 10s
    database: 6
    lettuce:
      pool:
        maxIdle: 8
        minIdle: 2
        maxActive: 4
        maxWait: 6000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://node1:3306/lgd_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: leguandian
    password: LeGuan@diaN888
    initial-size: 4
    max-active: 8
    min-idle: 2
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 16
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    filters: stat,wall

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl